name: CI/CD pipeline

on:
    push:
        branches:
            - main
        paths:
            - 'index.html'

jobs:
    build-push-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: docker reg log-in
              uses: docker/login-action@v2
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ secrets.DOCKER_USERNAME}}
                password: ${{ secrets.DOCKER_PASSWORD}}

            - name: build & push docker img
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                tags: tomiabr/nginx-img:lastest

            - name: run docker container
              run: docker run -d -p 80:80 --name nginx tomiabr/nginx-img:lastest

            - name: display index.html
              run: |
                echo "index.html content"
                curl http://localhost

            - name: stop docker container
              run: docker stop nginx